services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: [ 'controller.service_arguments' ]

    App\Domain\Model\Repository\UserRepository:
        tags: [ 'doctrine.repository_service' ]

    App\Infrastructure\Security\UserProvider:
        arguments:
            - '@doctrine.orm.entity_manager'

    App\Application\CommandHandler\Registration\RegisterUserCommandHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@security.password_hasher'

    App\Infrastructure\Controller\AuthController:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
            $userProvider: '@App\Infrastructure\Security\UserProvider'
            $passwordHasher: '@security.password_hasher'

    App\Application\CommandHandler\Product\CreateProductCommandHandler:
        tags:
            - { name: messenger.message_handler }

    App\Application\CommandHandler\Product\GetAllProductsCommandHandler:
        arguments:
            $productRepository: '@App\Domain\Model\Repository\ProductRepository'
